feat(tfnotify): Initial tfnotify asdf plugin from asdf template repository

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,45 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+architecture=""
+case $(uname -m) in
+i386)
+  architecture="386"
+  ;;
+i686)
+  architecture="386"
+  ;;
+x86_64)
+  architecture="amd64"
+  ;;
+arm64)
+  architecture="arm64"
+  ;;
+*)
+  fail "asdf-${TOOL_NAME} only supports 386, x86_64, and arm64 system architectures"
+  ;;
+esac
+
+os_distribution=""
+case $(uname -s) in
+Darwin)
+  os_distribution="darwin"
+  ;;
+Linux)
+  os_distribution="linux"
+  ;;
+*)
+  fail "asdf-${TOOL_NAME} only supports Darwin and Linux OS distributions"
+  ;;
+esac
+
+release_file="${TOOL_NAME}_${os_distribution}_${architecture}.tar.gz"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
